### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by orhun** [ShenMian/tracker#17]
Hey, very impressive tool!

It would be nice to create GitHub releases so that it can be packaged for various distributions 🐻 (e.g. Arch Linux)

Cheers!

**Comment by ShenMian** [comment]
Thanks for your suggestion, I have added GitHub Action that automatically creates Release and uploads executable files https://github.com/ShenMian/tracker/commit/497d0c097b80f8dcd351db64e397b6cff3699a99.

**Comment by orhun** [comment]
Awesome! I packaged `tracker` for the AUR here: https://aur.archlinux.org/packages/tracker

I can send a PR for adding instructions to README if you want :)

**Comment by ShenMian** [comment]
Thanks for packaging it to AUR.
I'm happy to accept PRs 😄
