### ISSUE TITLE
Add Tracker.exe as a 'release'

### ISSUE THREAD

**Issue by Stefan-Meeuwessen** [ShenMian/tracker#18]
Good day mate,

Saw your post on Linkedin and decided to check out this repository. It's a great idea and inspired me to make an application like this in Rust as a hobby project. However, whilst looking a this repository I noticed this repository is still a bit barebones. It's usually quite nice to add the ``/target/debug/tracker.exe`` as a standalone release so the user doesn't have to build the tool themselves or doesn't have to search for the ``.exe`` in the sub-directories.

Thanks for building and sharing this tool! :)

~ thatsleepyman

**Comment by ShenMian** [comment]
Thanks for your suggestion, I have added GitHub Action that automatically creates Release and uploads executable files https://github.com/ShenMian/tracker/commit/497d0c097b80f8dcd351db64e397b6cff3699a99.

**Comment by ShenMian** [comment]
@thatsleepyman Could you please share the link to the Linkedin post you mentioned? I didn't post it but I want to take a look :D

**Comment by Stefan-Meeuwessen** [comment]
Ah, well, here it is:
[Linkedin Link](https://www.linkedin.com/feed/update/urn:li:activity:7271830133022367744/)
